# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Lywsale' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Lywsale

  inhibit_all_warnings!
  
  pod 'AFNetworking'
  pod 'ReactiveObjC', :inhibit_warnings => true
  pod 'Masonry'
  pod 'SDAutoLayout'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'MBProgressHUD+DK'
  pod 'SDWebImage'
  pod 'DKViewPage'
  pod 'NinaPagerView'
  
end
